#!/usr/bin/env zsh

# Navigation
meh - h : yabai -m window --focus west
meh - j : yabai -m window --focus south
meh - k : yabai -m window --focus north
meh - l : yabai -m window --focus east

# Moving windows
fn + meh - h : yabai -m window --warp west
fn + meh - j : yabai -m window --warp south
fn + meh - k : yabai -m window --warp north
fn + meh - l : yabai -m window --warp east

# Float and center winvow
meh - c : yabai -m window --grid 4:4:1:1:2:2 || yabai -m window --toggle float; yabai -m window --grid 4:4:1:1:2:2

# Rotate windows clockwise and anticlockwise
meh - r : yabai -m space --rotate 270
fn + meh - r : yabai -m space --rotate 90

# Rotate on X and Y axis
meh - x : yabai -m space --mirror x-axis
meh - y : yabai -m space --mirror y-axis

# Test if yabai is enabled or not
meh - 3 : if [ (yabai -m query --spaces --space | jq -r .type) = "float" ]; osascript -e 'display alert "yabai is not enabled"'; else; osascript -e 'display alert "yabai is enabled"'; end
# Turn yabai on or off for current space
meh - 4 : yabai -m space --layout (yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "float" else "bsp" end');\
          osascript -e 'display notification "Toggling yabai on or off"'
# Toggle between stack and bsp for current space
meh - 5 : yabai -m space --layout (yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "stack" else "bsp" end');\
          osascript -e 'display notification "Toggling between bsp and stack"'

# Float / unfloat window
hyper - space : yabai -m window --toggle float

# meh - f : yabai -m window --toggle zoom-fullscreen
fn + meh - f : yabai -m window --toggle native-fullscreen

# Stacking
meh - return : yabai -m window --focus stack.next || yabai -m window --focus stack.first
meh - backspace : yabai -m window --focus stack.prev || yabai -m window --focus stack.last

## Stacking - directions
meh - a : yabai -m window --stack west
meh - s : yabai -m window --stack south
meh - w : yabai -m window --stack north
meh - d : yabai -m window --stack east

# Create/destroy spaces
# meh - 9 : yabai -m space --create
# meh - 0 : yabai -m space --destroy

# move windows
meh - 9 : yabai -m window --space prev;\
          yabai -m space --focus prev
meh - 0 : yabai -m window --space next;\
          yabai -m space --focus next
fn + meh - 9 : yabai -m space --move prev
fn + meh - 0 : yabai -m space --move next

############## Extras #######################
# Spaces: Ctrl + [NUM]
#lctrl - 1 : yabai -m space --focus 1
#lctrl - 2 : yabai -m space --focus 2
#lctrl - 3 : yabai -m space --focus 3
#lctrl - 4 : yabai -m space --focus 4
#lctrl - 5 : yabai -m space --focus 5
#lctrl - 6 : yabai -m space --focus 6
#lctrl - 7 : yabai -m space --focus 7
#lctrl - 8 : yabai -m space --focus 8
#lctrl - 9 : yabai -m space --focus 9
#lctrl - 0 : yabai -m space --focus 10

fn + lctrl - 1 : yabai -m window --space 1
fn + lctrl - 2 : yabai -m window --space 2
fn + lctrl - 3 : yabai -m window --space 3
fn + lctrl - 4 : yabai -m window --space 4
fn + lctrl - 5 : yabai -m window --space 5
fn + lctrl - 6 : yabai -m window --space 6
fn + lctrl - 7 : yabai -m window --space 7
fn + lctrl - 8 : yabai -m window --space 8
fn + lctrl - 9 : yabai -m window --space 9
fn + lctrl - 0 : yabai -m window --space 10

# Monitors
ctrl + cmd - 1 : yabai -m display --focus 1
ctrl + cmd - 2 : yabai -m display --focus 2
ctrl + cmd - 3 : yabai -m display --focus 3
ctrl + alt - 1  : yabai -m window --display 1;\
                  yabai -m display --focus 1
ctrl + alt - 2  : yabai -m window --display 2;\
                  yabai -m display --focus 2
ctrl + alt - 3 : yabai -m window --display 3;\
                  yabai -m display --focus 3
